/*
*  This program is free software; you can redistribute it and/or modify
*  it under the terms of the GNU General Public License as published by
*  the Free Software Foundation; either version 2 of the License, or
*  (at your option) any later version.
*
*  This program is distributed in the hope that it will be useful,
*  but WITHOUT ANY WARRANTY; without even the implied warranty of
*  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*  GNU Library General Public License for more details.
*
*  You should have received a copy of the GNU General Public License
*  along with this program; if not, write to the Free Software
*  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
*/

#ifndef _MESSAGESFRAME_H
#define _MESSAGESFRAME_H


#include "wx/frame.h"
#include "wx/textctrl.h"


/**
* Preferences used by this class
**/
#define PREF_MESSAGESFRAME_FRAMEWIDTH    wxT("MessagesFrame.FrameWidth")
#define PREF_MESSAGESFRAME_FRAMEWIDTH_DV 500

#define PREF_MESSAGESFRAME_FRAMEHEIGHT    wxT("MessagesFrame.FrameHeight")
#define PREF_MESSAGESFRAME_FRAMEHEIGHT_DV 400


// This class allows the user to see the messages generated by the app
// It's a signleton
class MessagesFrame : public wxFrame
{
protected:
	static MessagesFrame *mInstance;

	wxTextCtrl *mTextCtrl;


	MessagesFrame(wxWindow *parent);
	~MessagesFrame(void);


	// --- Events
	void OnClose(wxCloseEvent& event);


public:
	// Singleton pattern
	static MessagesFrame* GetInstance(wxWindow* parent);
	static void           DestroyInstance(void);

		void Toggle(void);
	static void OnNewMessage(void);


private:
	DECLARE_EVENT_TABLE()
};


#endif /* _MESSAGESFRAME_H */
